
spring:
  application:
    name: tennis-match
  profiles:
    active:
      - kmgyu
  datasource:
    url: jdbc:mysql://localhost:3306/tennis
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop    # 개발 중에는 create-drop 사용
    show-sql: true         # 실행되는 SQL 로그 출력
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  devtools:
    restart:
      exclude: static/**,public/**,resources/**,META-INF/**,*.properties

  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

  server:
    error:
      whitelabel:
        enabled: false
    port: 8080

## jwt
jwt:
  secret: MySuperSecretKeyForJwtSigning123456
  expiration: 86400000


  ## log
logging:
  level:
    org:
      mybatis: debug